name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: sayyid5416/pyinstaller@v1
      with:
          python_ver: '3.9'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Productimages.exe'
          options: --onefile, --name "productimages", 
